version: 0.2
env:
  variables:
    CI: "true"
cache:
  paths:
    - /root/.npm/**/*
phases:
  install:
    commands:
      - npm install -g npm@latest
      - npm install
  build:
    commands:
      - npm run build
  # post_build:
  #   commands:
  #     - aws s3 cp --recursive ./build s3://  give me a bucket
